config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'splashes#index'
  
  resources :categories, only: [:index, :new, :show, :create]
  resources :activities, only: [:new, :show, :create]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, User, id: user.id
    can :manage, Category, author: user
    can :manage, Activity, author: user
    can :manage, ActivityCategory, category_id: { author_id: user.id }
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :activity_categories, foreign_key: :activity_id

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/activity_category.rb
class ActivityCategory < ApplicationRecord
  belongs_to :activity
  belongs_to :category
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :activity_categories, foreign_key: :category_id

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :activities, foreign_key: 'author_id'
  has_many :categories, foreign_key: 'author_id'

  validates :name, presence: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def new
    @activity = Activity.new
  end

  def create
    @activity = current_user.activities.new(activity_params)

    if @activity.save
      @activity_category = @activity.activity_categories.create(activity_category_params)
      flash[:notice] = 'activity was successfully created.'
    else
      flash[:alert] = "Failed to add activity - #{@activity.errors.full_messages.first}"
    end
    redirect_to "/categories/#{@activity_category.category_id}"
  end

  def destroy
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def activity_category_params
    params.require(:activity).permit(:category_id)
  end

  def activity_params
    params.require(:activity).permit(:name, :amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    categories_path
  end

  def after_sign_out_path_for(_resource)
    root_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  def index
    @categories = current_user.categories.includes(activity_categories: :activity)
  end

  def show
    @category = Category.find_by_id(params[:id])
    @activity_categories = @category.activity_categories.includes(:category, :activity).order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = current_user.categories.new(category_params)
    respond_to do |format|
      format.html do
        if @category.save
          flash[:notice] = 'Category was successfully created.'
        else
          flash[:alert] = "Failed to add category - #{@category.errors.full_messages.first}"
        end
        redirect_to categories_path
      end
    end
  end

  def destroy
    category = Category.find(params[:id])
    if category.destroy
      flash[:notice] = 'category deleted!'
    else
      flash[:alert] = "Failed to remove category - #{recipe.errors.full_messages.first}"
    end
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/splashes_controller.rb
class SplashesController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def total_amount(array)
    total = 0
    array.each do |item|
      total += item.activity.amount
    end
    total
  end
end

app/views/_partials/_category_header.html.erb
<div class="card w-100 mt-1">
  <div class="g-0 d-flex align-items-center p-2">
    <div class="w-25">
      <%= image_tag(category.icon, alt: "category icon", class: "category-icon") %>
    </div>
    <div class="w-50 mx-3">
      <div class="card-body">
        <h5 class="display-6 fw-bold text-center"><%= category.name %></h5>
      </div>
    </div>
    <div class="w-25 ml-4 pl-4">
      <h4 class="fw-bold">$ <%= total_amount(category.activity_categories) %></h4>
    </div>
  </div>
</div>

app/views/_partials/_header.html.erb
<nav class="navbar mobile-header">
  <%= link_to back_path, class: "back-button" do%>
    <span><i class="fa fa-arrow-left"></i></span>
  <% end %>
  <h3 class="header-title fs-5"><%= title %></h3>
  <%= link_to destroy_user_session_path, method: :delete, class: "btn text-light" do%>
    <span>Log out</span>
    <i class="fa fa-sign-out"></i>
  <%end%>
</nav>

app/views/_partials/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to "MY RECIPE", root_path, class: 'ps-4 mx-5 is-link display-4' %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            About
          </a>
          <a class="navbar-item">
            Jobs
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-primary" %>
          <%= link_to "Edit Profile", edit_user_registration_path, class: "button is-light" %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/_partials/buttons/_add_new_item.html.erb
  <%= link_to new_path, class: "btn btn-add", id: "add" do%>
    <span><%= label.upcase %></span>
  <% end %>

app/views/_partials/cards/_activity.html.erb
<div class="card activity-container">
  <div class="g-0 d-flex align-items-center p-2">
        <h3 class="activity-detail">Transaction N°<%= activity_category.activity.id%></h3>
    <div class="w-50 mx-3">
        <h4 class="activity-body"><%= activity_category.activity.name %></h5>
    </div>
    <div class="w-50 ml-4 pl-4">
      <h5 class="activity-amount">$ <%= activity_category.activity.amount %></h4>
    </div>
  </div>
</div>

app/views/_partials/cards/_category.html.erb
<div class="card m-3">
  <div class="g-0 category-card">
    <div class="w-25">
      <%= image_tag(category.icon, alt: "category icon", class: "category-icon") %>
    </div>
    <div class="w-50 mx-3">
      <div class="card-body">
        <h5 class="card-title display-7 fw-bold"><%= category.name %></h5>
      </div>
      <span class="category-date"><%= category.created_at.strftime("%d %m %Y")%></span>
    </div>
    <div class="w-25 ml-4 pl-4">
      <h4 class="category-total">$ <%= total_amount(category.activity_categories) %></h4>
    </div>
  </div>
</div>

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name,  autofocus: true, required: true, placeholder: "Transaction Name", class: "form-control", id: "name"  %>
  </div>

  <div class="field">
    <%= form.number_field :amount, required: true, placeholder: "Add you amount", class: "form-control", id: "amount"  %>
  </div>

  <div class="form-group">
		<label for="food" class="form-label mr-4 display-5">Category</label>
		<%= form.select :category_id, current_user.categories.map { |category| [category.name, category.id]} ,  {}, { class: "form-select form-select-lg mb-3" }%> 
  </div>

  <div class="actions mt-5">
    <%= form.submit 'Save Transaction', class: "btn btn-add" %>
  </div>
<% end %>

app/views/activities/new.html.erb
<div>
  <%= render partial: "_partials/header", locals: { title: "New Transaction", back_path: categories_path } %>
  <%= render 'form', activity: @activity %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, autofocus: true, required: true, placeholder: "Category name", class: "form-control", id: "name" %>
  </div>

  <div class="field">
    <%= form.text_field :icon, required: true, placeholder: "Add icon URL", class: "form-control", id: "icon" %>
  </div>

  <div class="actions mt-5">
    <%= form.submit 'Save Category', class: "btn btn-add"%>
  </div>
<% end %>

app/views/categories/index.html.erb
<div class="catgories-container d-flex flex-column">
  <%= render partial: "_partials/header", locals: { title: "Your Categories", back_path: root_path} %>
  <div class="category-cards text-center">
    <%if @categories.empty? %>
    <h2 class="fw-bold mt-5 display-3">There is no category</h2>
    <p class="mt-3 display-7">Try to add one with the below button</p>
    <%else%>
      <% @categories.each do |category|%>
        <%= link_to category_path(category.id) do%>
          <%= render "_partials/cards/category", category: category%>
        <%end%>
      <%end%>
    <%end%>
  </div>
  <%= render partial: "_partials/buttons/add_new_item", locals: { label: "Add New Category", new_path: new_category_path } %>
</div>

app/views/categories/new.html.erb
<div>
  <%= render partial: "_partials/header", locals: { title: "New Category", back_path: categories_path } %>
  <%= render 'form', category: @category %>
</div>

app/views/categories/show.html.erb
<div>
  <%= render partial: "_partials/header", locals: { title: "Your Transactions", back_path: categories_path} %>
  <%= render partial: "_partials/category_header", locals: { category: @category, activity_categories: @activity_categories } %>

  <div class="text-center">
    <%if @activity_categories.empty? %>
    <h2 class="fw-bold mt-5 display-6">There Is No Transactions</h2>
    <p class="mt-3 display-7">Try to add one with the below button</p>
    <%else%>
      <h2 class="fw-bold mt-5 display-6">Recent Transactions</h2>
      <% @activity_categories.each do |activity_category|%>
          <%= render partial: "_partials/cards/activity", locals: { activity_category: activity_category } %>
      <%end%>
    <%end%>
  </div>
    <%= render partial: "_partials/buttons/add_new_item", locals: { label: "Add Transaction", new_path: new_activity_path } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%# CSS frameworks%>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if user_signed_in? %>
      <% if notice %>
      <p class="alert alert-primary"><%= notice %></p>
      <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
</div>
<% end %>
<% if flash[:alert] %>
<div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%= link_to "Users", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Posts", posts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Comments", comments_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Likes", likes_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <% if current_user %>
            <%= button_to "Logout", destroy_user_session_path(), method: :delete, class: "btn btn-warning" %>
        </li>      
          <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>          
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/splashes/index.html.erb
<div class="bg-image splash-bg shadow-1-strong rounded d-flex justify-content-center align-items-end">
  <div class="sign_in_container text-center">
    <% if user_signed_in? %>
      <h3 class="welcome-title">Welcome, <%= current_user.name.capitalize%></h3>
      <p class="welcome-body">You are signed in</p>
      <%= link_to 'Go To Categories', categories_path, class: "login-btn btn mb-4", id: "go-categories" %>
      <%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "btn btn-light mb-2" %>
    <%else%>
      <%= link_to 'LOG IN', new_user_session_path, class: "login-btn btn mb-4 py-3" %>
      <%= link_to 'SIGN UP', new_user_registration_path, class: "btn btn-light mb-2 py-3" %>
    <%end%>
  </div>
</div>